"""Add product type and thc fields

Revision ID: bd3624983376
Revises: 7f8a2c9d1e5b
Create Date: 2025-12-26 19:54:37.391732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bd3624983376'
down_revision: Union[str, None] = '7f8a2c9d1e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_categories_active_info', table_name='categories')
    op.drop_index('idx_categories_parent_id', table_name='categories')
    op.drop_constraint('fk_categories_parent_id', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    op.add_column('products', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('thc', sa.Numeric(precision=4, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'thc')
    op.drop_column('products', 'type')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('fk_categories_parent_id', 'categories', 'categories', ['parent_id'], ['id'], ondelete='RESTRICT')
    op.create_index('idx_categories_parent_id', 'categories', ['parent_id'], unique=False)
    op.create_index('idx_categories_active_info', 'categories', ['is_active', 'is_info_only'], unique=False)
    # ### end Alembic commands ###
